name: Build Ionctl (Linux)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/src.sln

      - name: Publish Ionctl (non-AOT, self-contained)
        run: |
          dotnet publish ./src/Ionctl/Ionctl.csproj \
            -c Release \
            -r linux-x64 \
            /p:SelfContained=true \
            /p:PublishSingleFile=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            -o ./ionctl-out

      - name: Rename binary
        run: mv ./ionctl-out/Ionctl ./ionctl-linux-x64 && chmod +x ./ionctl-linux-x64

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./ionctl-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
